base_url = "https://byronhambly.com"
title = "Byron Hambly"

compile_sass = true
highlight_code = false
build_search_index = false

[extra]
links = [
    { text = "dev blog", url = "https://hambly.dev", hostname = "hambly.dev"},
    { text = "@delta1", url = "https://github.com/delta1", hostname = "github.com"},
    { text = "email", url = "mailto:byron.hambly@gmail.com", hostname = "gmail.com"},
    { text = "keybase", url = "https://keybase.io/byronhambly", hostname = "keybase.io"},
    { text = "linkedin", url = "https://www.linkedin.com/in/byronhambly/", hostname = "linkedin.com"},
]
